### ISSUE TITLE
Le parisien - Le figaro

### ISSUE THREAD

**Issue by blaireau1er** [reek/anti-adblock-killer#1234]
Hi

http://www.leparisien.fr/
![parisien](https://cloud.githubusercontent.com/assets/18113032/14074732/8b7d9e62-f4d3-11e5-8d21-113221ba19de.JPG)

http://www.lefigaro.fr/
![le figaro](https://cloud.githubusercontent.com/assets/18113032/14074777/db938a10-f4d3-11e5-947e-e0bfbad1c625.JPG)

Thanks

**Comment by reek** [comment]
Already killed, update AakList

**Comment by zorro3210** [comment]
I woud llike to reopen it since it is blocked again
http://www.lefigaro.fr/actualite-france/2016/09/20/01016-20160920ARTFIG00247-deux-nouveaux-adolescents-interpelles-apres-la-fausse-alerte-attentat-de-paris.php


![image](https://cloud.githubusercontent.com/assets/8364468/18675950/478139f6-7f54-11e6-9e23-0afea416c440.png)

**Comment by mapx-** [comment]
no issues here (easylist, liste FR)

**Comment by reek** [comment]
No detected, probably fixed by Easylist or Liste FR
