### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1309]
solution 
purepc.pl#@#[class*="reklama"]
purepc.pl#@#.reklama

**Comment by Piter432** [comment]
The warning still shows up :/

**Comment by reek** [comment]
@Piter432 
take screenshot

**Comment by Piter432** [comment]
Here you are:
![2016-4-28 16 11 39](https://cloud.githubusercontent.com/assets/5713816/14888888/970d9650-0d5c-11e6-89ee-7a519b88b56a.png)

I have the latest uBlock Origin, newest Anti-Adblock killer filters list version, latest Tampermonkey for Chrome and latest version of Anti-Adblock killer userscript. Only Chrome isn't newest, because I'm now on Windows XP.

**Comment by MajkiIT** [comment]
Try add this ==> 
purepc.pl#@#[class*="reklama"]

**Comment by Piter432** [comment]
@MajkiIT: Still doesn't work :/

**Comment by bourne9** [comment]
It's just you, I dont see that message ever popping up. Also for the love of god, please get Windows 7 atleast. XP is fucking dead.

**Comment by Piter432** [comment]
@bourne9: LOL. It's not just me. The same is on my mom's laptop, which have... Windows 7 64-bit on Firefox with newest Greasemonkey Anti-Adblock killer filters list and userscript :)

**Comment by Piter432** [comment]
@bourne9: Ah, I'm not sure you see that on my screenshot, but my GPU will die soon and I don't have money to buy completely new & powerful PC, because it's expensive in Poland and my current PC needs almost (new HDD's can be not included in my new PC) full new components. Unless you want to buy new PC for me, lol :v

**Comment by bourne9** [comment]
@Piter432 I didn't mention new PC, just download Windows 7 from torrents ran a clean installation. 

Secondly, my PC is 11 years old and still runs like a horse with Windows 10, so please don't make excuses of a dead PC, if you wanted Windows 7 you could have installed it. GPU is useless unless you play heavy duty games. I don't even have a GPU and my PC is powerful enough to run Chrome + uB0 + AAK. You don't need a new PC, you need a new OS, simple as that and I saw your screenshot, but this issue has nothing to do with your GPU or any hardware, so why are you even bringing that up in the first place ?

**Comment by Piter432** [comment]
@bourne9:
> I didn't mention new PC

But your comment sounded like that.

---
> just download Windows 7 from torrents and run a clean installation.

I hate cracking and pirating, so no. I WILL NOT crack Windows 7 and even any other paid OS for PC. Also, I don't have powerful internet, so downloading a file, which its size have some GB isn't an option, especially when because of my GPU state, my PC can show BSoD.

---
> Secondly, my PC is 11 years old and still runs like a horse with Windows 10

Yea, yea. And some people have problems with Windows 10 on PCs similiar to yours. I will not experiment with OS on my one and only one PC.

---
> please don't make excuses of a dead PC

Do you want to show you my specifications of PC? :) Also, I'm IT geek so I NEED a good PC and that's why I wrote about new PC.

---
> if you wanted Windows 7 you could have installed it

Yes, I could. But in those times I didn't know almost the same of the IT as today, especially I was younger.

---
> You don't need a new PC, you need a new OS

I NEED a new PC. Why? I wrote that earlier. Read carefully, because I don't want to say the same many times.

---
> simple as that

So, if you think that my situation is simple, come to me. We'll see, what you will tell then :)

---
> I saw your screenshot, but this issue has nothing to do with your GPU or any hardware, so why are you even bringing that up in the first place ?

Lel, I think you don't know what are you writing about. I wrote that the STRANGE LOOK of MY SCREENSHOT is because of MY GPU, and not that because of this issue is something wrong with my GPU as you can see on my screenshot. Please read with understanding, dude.

**Comment by reek** [comment]
@Piter432 
This rule <code>purepc.pl#@#.reklama</code> is good , please check https://github.com/reek/anti-adblock-killer#help

**Comment by bourne9** [comment]
@Piter432 I thought I was trying to help, but instead you're the guy who simply loves to make excuses and justify his actions yet take time to whine about it here. That screenshot could indicate a problem with your display too and not necessarily your GPU, but yet here you are trying to prove yourself correct and continue to whine, go ahead kid, you do that, you sound like the guy from sa-mp forums, never trying to understand others, always trying to justify yourself and the way you split my posts, you sound like a troll who needs to be fed, my bad, I won't feed you anymore.

**Comment by bourne9** [comment]
@reek it's userside, doesn't happen to me, so probably it's him.

**Comment by Piter432** [comment]
@reek & @bourne9: Here is screen from my mom's laptop, who use Windows 7 64-bit SP1 and newest Firefox. The warning shows up even on this machine. Any more questions? :)))))))))
![2016-05-10 15 19 46 pepc blk ak](https://cloud.githubusercontent.com/assets/5713816/15148792/291c1e4a-16c7-11e6-8aca-74f7b978414b.png)

**Comment by F4z** [comment]
@Piter432 Spróbuj tej reguły <code>purepc.pl#@#[class$="reklama"]</code>
Jeśli jednak nie pomoże, to podaj wszystkie listy filtrów, z których korzystasz, albo screena z loggera uBlocka.
Bo tak to można zgadywać tylko :)

**Comment by Piter432** [comment]
@F4z: This rule works! :) Thank you, dude :)
______

Reguła działa! :) Dzięki, ziomek :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
