### ISSUE TITLE
dogry.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1379]
@@||dogry.pl/ads.html$subdocument

**Comment by bourne9** [comment]
no anti adblock detector found at that document or at that website, and also post in the appropriate reporting format mentioned here - https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require

**Comment by F4z** [comment]
@bourne9 
https://dogry.pl/world-of-tanks/

![image](https://cloud.githubusercontent.com/assets/11742596/14895871/333e1022-0d7b-11e6-9337-4bc31f226beb.png)

**Comment by MajkiIT** [comment]
@F4z Thanks

**Comment by bourne9** [comment]
@F4z  That seems to happen only when we're clicking on the category "the games players love" and the adblock detection is hidden with a document page which loads as an iframe, thats why the .html file is never located and that's why it didn't appear in the Network Tab via Inspect Element. Detection is a bit smarter than the average adblock detection scripts we have seen here in the issues and that filter works. Good find.

**Comment by reek** [comment]
thanks @MajkiIT
