### ISSUE TITLE
Topserialy.sk

### ISSUE THREAD

**Issue by jackdizajn** [reek/anti-adblock-killer#1399]
The anti-adblock starts working when i see this. Somefing is wrong :(
Where is problem ?
Example video url:
http://www.topserialy.sk/serialy/mike-molly-s01e01
![adblock](https://cloud.githubusercontent.com/assets/19212316/15055316/22cb9160-130c-11e6-8882-c4fe845b8206.png)

**Comment by bourne9** [comment]
@jackdizajn Filter - `||topserialy.sk/js/jquery.js$script`
`

**Comment by Endlex** [comment]
@bourne9 you are idiot? :D
You cant just block whole jquery ... nothing will work, start using brain, pls.

**Comment by bourne9** [comment]
@Endlex You're a noob retard, it's not a jquery file you goddamn faggot ! Open the file and you will see it sets the adblocking variable, that's the anti adblock detection and we have to block it, you use brain first dumb moron and I tested what I post and it everything works, you better start using ur brain first noob kid.

**Comment by Endlex** [comment]
@bourne9 you are so retarded as I thought, "everything works" no, nothing work you moron, it's jquery, no anti-adblock, filters doesn't work on /serialy, marking epizodes doesn't work, not even single JS work, so shut your mouth your nobrain imbecil

**Comment by bourne9** [comment]
@Endlex Sucka big fat dick you noob faggot, it works. Here's the screen shot, you're nothing more than a fucking troll and an imbecile. You don't even know what jquery is in the first place dumb nigger.

![fuck u Endlex](https://i.gyazo.com/282e3cf6c2ae89947cb83398d882055c.png)

**Comment by Endlex** [comment]
@bourne9 jesus, how long until you fcking retarded brain will get it? Yes videos work, but javascript on website topserialy.sk not, because you are so fcking retarded and you blocked whole js.
Search doesn't work, filters doesn't work, not even single javascript.

WAKE UP YOU FUCKIGN IDIOT.
you dont even know what is jquery.

**Comment by reek** [comment]
@jackdizajn 
I'll kill it, thanks

@bourne9 
when you do not know, let me do.

@jackdizajn 
@bourne9 
no need to insult you.

**Comment by bourne9** [comment]
@reek, no need to put a -1 on the solution that actually works, and that moron started it so don't tell me what to do, btw I reported his profile on github already. I already know and I posted it, whethe you accept it as a solution or not that's upto you, it's works perfectly.

**Comment by bourne9** [comment]
@Endlex test

**Comment by reek** [comment]
@bourne9 
This is a bad solution because jquery does not contain anti-adblock and the site to need to function properly.

I appreciate that you are more respectful to the person to whom you speak.

**Comment by bourne9** [comment]
@reek, site functions perfectly without and with the script, I personally tested. The site functions perfectly well except for the search, so I removed the filter and the search STILL DIDn't work, so the site's screwed up, not the filter, I thought you were better than this, taking the word of trolling retard instead of checking up on yourself. I never post filters without checking the functionality, you should know that. That jquery is only in the name, it' inserting code which checks for adblock and when it's blocked, it doesn't appear and the video can be played, nothing's bad about it except your opinion.

Secondly, I'm an American, that asshole started the insults so I always fire back, got it ? Dont worry. I reported his trolling ass and the github team blocked it. Respect has to be earned. He dis-respected and tried to troll the conversaion, obviously he got beat and he won't be getting any respect, he has earn it first. If you want respect, offer respect first, that's the policy of mine.

I will appreciate if you stop neg voting the filter and taking the troll's side instead of checking out yourself. The site works perfectly except for the search which even without filter is bugged and doesn't work.

**Comment by webflowx** [comment]
@bourne9 

"The site functions perfectly"
You are joking?
Jquery is used there for many things and you just blocked it, congratulations.

Website worked fine without that filter. With it nothing work, there is many thing which works only because of javascript, search, filters (/serialy), marking epizodes as viewed, turn off light, resize video, some js function is also used on comments, so agian congratulations, you apparently dont know what are you doing.

Better do nothing ... because you know nothing.

**Comment by bourne9** [comment]
@webflowx Congratulations on creating multi accounts, retard or should I call you Endlex ! Dont worry it will get reported and you will be kicked out soon hahaha.

I can smell a multi-accounter and a ban evader a mile away. Adios moron!

**Comment by reek** [comment]
@bourne9 
arrested childishness >:(

**Comment by webflowx** [comment]
@bourne9 
Now I really don't know.... should I laugh or cry? Only one who deserve report is you.
Even @reek told you that your filter is useless, I'm told you that also.
I'm on that website every day and I know what doesn't work with your useless filter.

You can't even recognize  what is anti-adblock script and what is jquery, stop pls, you don't know basic things.

It's like ...  "hey, we can block jquery on every website, they don't need javascript".

Again congratulations, and again "like" your own post again.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
