### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by sonisgunu** [reek/anti-adblock-killer#1600]
https://openload.co
Google Chrome
Tampermonkey
Adblock
AakList
"The publisher of this file doesnt allow adblock, please disable and reload !"
http://prntscr.com/bhfv07

**Comment by Giwayume** [comment]
Need a link to the file you're having a problem with. Can't reproduce by simply visiting https://openload.co/.

**Comment by xyzzy-xyzzy** [comment]
I want to confirm this too.

Example:
https://openload.co/f/0gRrdmQtSKM/Mysteries.at.the.Museum.S11E01.720p.HDTV.x264-DHD.mkv

Somehow, with ad blockers installed (don't even need them enabled) clicking openload links to download results in downloading a file named Komp.mp4 which is not the desired file but a movie with a banner complaining about hot links.

This problem is also issue [#1106](https://github.com/adsbypasser/adsbypasser/issues/1106) reported  (not by me) for adsbypasser.

**Comment by xyzzy-xyzzy** [comment]
Update.  It was just pointed out in adsbypasser [issue #1106](https://github.com/adsbypasser/adsbypasser/issues/1106) that _disabling_ adsbypasser allows the openload downloads to work.

**Comment by reek** [comment]
@sonisgunu 
Already killed by Aak
