### ISSUE TITLE
tv.zing.vn

### ISSUE THREAD

**Issue by izark99** [reek/anti-adblock-killer#1764]
http://tv.zing.vn/video/Dieu-Tuyet-Nhat-Cua-Chung-Ta-Tap-23/IWZCWOI7.html
Vivaldi 
Adblock Plus
EasyList + AakList

**Comment by loveleeyoungae** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by X01X012013** [comment]
It seems that this has Geo Lock.

**Comment by reek** [comment]
@izark99 
This content has been removed

**Comment by loveleeyoungae** [comment]
It's just because the site blocks IP not from Vietnam. 
And actually, the AAK script works fine. I guess the OP was blocked because he didn't install AKK Userscript (as he didn't mention any "*monkey" extension his post).
However, there're still some ads...
<img width="937" alt="tvzing" src="https://cloud.githubusercontent.com/assets/11622233/16922818/68e4cc74-4d41-11e6-8614-2206ee55c641.png">
