### ISSUE TITLE
*.gamepedia.com

### ISSUE THREAD

**Issue by ErmanSayin** [reek/anti-adblock-killer#1783]
http://terraria.gamepedia.com/Terraria_Wiki (there's also other websites on other subdomains, the backend is all the same though)
http://i.imgur.com/ttK3PO7.png
Google Chrome 53.0.2785.8
Tampermonkey
uBlock Origin
Easylist + uBlock filters + Aaklist + some others

**Comment by X01X012013** [comment]
This is a straight up ad instead of trying to detect AdBlocker. Remove div with id "atflb" will be the fix, but I'm not sure why `gamepedia.com###atflb` doesn't work... Even the code generated by AdBlock Plus hide element button doesn't seem to work... I guess I'll have to add it into my script... The element will be removed when page loads which means it can show for a few seconds. 
If you want, you can use this until we find a better solution: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by X01X012013** [comment]
Reek is back?

**Comment by reek** [comment]
Hi,
Yes, I was a bit busy recently but I will come back little by little.

thank you for helping the user during that time

2016-11-06 22:21 GMT+01:00 X01X012013 <notifications@github.com>:

**Comment by mikhoul** [comment]
Welcome back @reek !   :smile_cat:
