### ISSUE TITLE
livenewschat.eu

### ISSUE THREAD

**Issue by LarMer** [reek/anti-adblock-killer#1789]
http://www.livenewschat.eu/
http://imgur.com/svAWhyH
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

The page loads fine, then about 15-20 seconds after being on the page, the whole page will be replaced with an anti-adblock warning. It's blocked by Blockadblock.com. That website has the very same block, and the anti-adblock-killer isn't removing it.

**Comment by X01X012013** [comment]
This one can be removed simply by disabling system function eval(), which is necessary for BlockAdBlock to run. But it may not work well on some sites since it may happen that the website needs eval(). The website livenewschat.eu seems to not need eval() to run, so we can simply disable it. 
While waiting for a proper generic BlockAdBlock to be developed, you can use my temporary solution:  https://x01x012013.github.io/AdBlockProtector/

**Comment by mapx-** [comment]
see
https://github.com/reek/anti-adblock-killer/issues/1797#issuecomment-234213231

**Comment by reek** [comment]
Already fixed by Easylist
