### ISSUE TITLE
META: Does anyone know if everything's OK w/ @Reek?

### ISSUE THREAD

**Issue by TPS** [reek/anti-adblock-killer#2359]
@Reek had usually been quite involved on GitHub, but he's been completely silent for months. Does anyone @all have solid indication everything is well?

**Comment by rjkpa** [comment]
Since I can't find the thread which you grave dug and asked for citation, let me `cite` some logic about reek's disappearance. 

- Reek's MIA and his last commit was on July 6th. His last comment was on July 21st.

- He hasn't posted or did anything since July and his last release was version 9.8, when he was active we would receive a monthly release.

- He hasn't left a message or anything about his situation and has completely abandoned this project.

There, good enough for ya ? Whether you like it or not, he's gone and nobody knows IF he will ever come back to revive this dead horse. Lastly, nobody needs this anymore, I removed it and it's working quite well even without reek's script; if you're using uBlock Origin or ABP, so you don't need this. Whenever you come across any anti adblocker, simply report to forums.lanik.us and they will post a filter and will add to Easylist. You might as well give up on reek who hasn't bothered to show his face or inform about the status of this project for months altogether.

**Comment by TPS** [comment]
Gee, "thanks."

This wasn't an issue about ~~*"Let's all go tell @Reek we don't need him,"*~~ but moreso, __"@Reek, you're generally rather chatty, but now silent as the grave.  Are you well?!"__

Comments like above cause dev replies like https://github.com/klausw/hackerskeyboard/issues/487#issuecomment-255540845, & must be why @GitHub is working on https://help.github.com/articles/github-community-guidelines/.  For humanity's sake, be civil & decent!

**Comment by TPS** [comment]
[Welcome back,](https://github.com/reek/anti-adblock-killer/commit/ad0fcedda225bd73ec6e515d0e66fd30ae0671b2#commitcomment-19729657) @Reek! :bow: :heart_eyes:

**Comment by TPS** [comment]
Was going to re-open, but #2092 will do....
