### ISSUE TITLE
all sites: script on ms edge

### ISSUE THREAD

**Issue by dchango** [reek/anti-adblock-killer#2365]
http://i.imgur.com/JrNgnMQ.png
Any sites having anti adblock stuff (i.e: xtube/kissanime,etc)
Microsoft Edge
Tampermonkey
uBlock Origin OR Adblock plus (tried both)
EasyList + AakList

**Comment by X01X012013** [comment]
Redirect loop? Is there any output in the console?

**Comment by mapx-** [comment]
kissanime:

this filter is working in ABP + edge
`@@||adsterra.com^$domain=kissanime.to`

search see easylist forum too
https://forums.lanik.us/viewtopic.php?p=107082#p107082

**Comment by stasjok** [comment]
I can confirm this.
Edge just crashes every time I opened many sites (for example: overclockers.ru, kinopoisk.ru) with Tempermonkey and this script. After every crash Edge tries to reload page without success. After two reloads it shows this error (picture from top message). Don't know if it's Edge or script issue. But I think browser shouldn't crash like this on js. I can't see console messages because dev tools disappears after every crash.

**Comment by reek** [comment]
@dchango 
Microsoft Edge not supported
