### ISSUE TITLE
https://blockadblock.com/

### ISSUE THREAD

**Issue by MolotovCherry** [reek/anti-adblock-killer#2539]
This is a new site which sells a service to other websites to automatically block adblockers. Confirmed that this not blocked with the anti-adblock-killer, latest as of this posting date.

**Comment by mapx-** [comment]
it's very old, search the issues
https://github.com/reek/anti-adblock-killer/issues/2348#issuecomment-258082447

**Comment by uBlock-user** [comment]
and it wont be blocked as there is no reason for it to be blocked. Nobody visits that website as it doesn't offer any useful content, so ffs! Just drop it! That website is for folks who want to use that script to block adblockers.

**Comment by MolotovCherry** [comment]
@uBlock-user The main point of my issue post was to maybe get the script itself blocked so that it will apply to any site that uses it, thus providing an invaluable use of this anti-adblock software. Anyways, mapx- offered a workable solution, thank you!

**Comment by uBlock-user** [comment]
There is no filter which can block the anti ad blocking software for all websites using this adblocking script. That's common sense! If you had searched, you would have known that already. Search before you post. BlockAdBlock topic has been posted around here for more than 3 times already in the past 7 days and people still don't search.

Here's the one for the website anyway, since you're so desperate to block the code on website. Will work on uBlock Origin only.

`blockadblock.com##script:inject(bab-defuser.js)`

This is what I meant by search before you post - https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=BlockAdBlock
