### ISSUE TITLE
cmmonitor.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#267]
http://www.cmmonitor.com/btc/
http://i.imgbox.com/DBFIxyz0.png
Chromium Version 43.0.2345.0 (64-bit)
uBlock 0.9.2.1 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy‎
Tampermonkey BETA 3.11.4615 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message:"<div class="blockmessage" style="min-width: 450px; max-width: 550px; margin: 0 auto; background-color: #fff; border-radius: 10px; padding: 25px; text-decoration: none; box-shadow: 0 0 25px 5px #999; color: #000; line-height: 20px;"><strong>Please disable your ad blocker!<br>Bitte deaktiviere Deinen Werbeblocker!<br>Veuillez desactiver votre bloqueur de publicite!<br>Por favor, desactive el bloqueador de anuncios!<br>Пожалуйста, отключите ваш блокировщик рекламы!</strong><br><br><br>This website is completely supported by revenue from ads, which is used to buy Bitcoins to distribute to users like you.<br><br>By blocking ads on our website, you are cutting off our only source of revenue and this will seriously affect our ability to continue distributing Bitcoins to our users.<br><br>Please disable your ad-blocking browser plugin/software for this page and then<br><a href="/btc/">click here</a><br>to refresh the page and collect your free Bitcoins.</div>"

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by vinctux** [comment]
Hey @reek,

The site apparently changed the design of the Anti-Adblock system, because it's returning the same message:
![cmmonitor](https://cloud.githubusercontent.com/assets/9408266/8411809/2e929dca-1e86-11e5-9573-c1c6a346ba23.png)

This inline-script is the problem:
```javascript
// Run after all the page elements have loaded
window.onload = function(){ 

// This will take care of asynchronous Google ads
setTimeout(function() { 

// We are targeting the first banner ad of AdSense
var ad = document.querySelector("ins.adsbygoogle");

// If the ad contains no innerHTML, ad blockers are at work
if (ad && ad.innerHTML.replace(/\s/g, "").length == 0) {

// Since ad blocks hide ads using CSS too
ad.style.cssText = 'display:block !important; position: fixed !important; top: -2px; left: 0px; width: 100%; height: 100%; background-color: #000; opacity: .95; filter: alpha(opacity=95); display: block; padding: 15% 0; text-align: center; font-family: arial; font-size: 14px; text-decoration: none; z-index: 99999;'; 

// You can put any text, image or even IFRAME tags here
ad.innerHTML = '<div class="blockmessage" style="min-width: 450px; max-width: 550px; margin: 0 auto; background-color: #fff; border-radius: 10px; padding: 25px; text-decoration: none; box-shadow: 0 0 25px 5px #999; color: #000; line-height: 20px;"><strong>Please disable your ad blocker!<br>Bitte deaktiviere Deinen Werbeblocker!<br>Veuillez desactiver votre bloqueur de publicite!<br>Por favor, desactive el bloqueador de anuncios!<br>Пожалуйста, отключите ваш блокировщик рекламы!</strong><br><br><br>This website is completely supported by revenue from ads, which is used to buy Bitcoins to distribute to users like you.<br><br>By blocking ads on our website, you are cutting off our only source of revenue and this will seriously affect our ability to continue distributing Bitcoins to our users.<br><br>Please disable your ad-blocking browser plugin/software for this page and then<br><a href="/btc/">click here</a><br>to refresh the page and collect your free Bitcoins.</div>';
}

}, 0); // The ad blocker check is performed 0 seconds after the page load 
};
```
A general and global solution would be to trick out the
```javascript
if (ad && ad.innerHTML.replace(/\s/g, "").length == 0)
```
if-statements, with manipulating the values of length for every ad place holder. This would avoid much Anti-AdBlock scripts to function properly.

I hope it helps.

**Comment by maynak00** [comment]
tested in chromium x64+tampermonkey beta+ublock origin
firefox stable+greasemonkey+ublock origin
no antiadblock notice.
@vinctux **full report please**
**report guide:**https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by vinctux** [comment]
@maynak00 Nice for you, but I see the notice still. I tested it on a Opera 30 with Ghostery, Tampermonkey and uBlock Origin and the appropriate lists and scripts. And if it is that important - I know the Report Guide - (which I think it is not, because if it were, then it would violate with another list, which it does, at least how I see it, **not**), here is the full list of them.
Filter lists:
* Adblock Warning Removal List‎
* Anti-Adblock Killer | Reek
* EasyList‎
* Peter Lowe’s Ad server list‎
* Basic tracking list by Disconnect‎
* EasyPrivacy‎
* Fanboy’s Enhanced Tracking List‎ 
* Malvertising filter list by Disconnect‎ 
* Malware Domain List‎
* Malware domains‎
* Malware filter list by Disconnect‎
* Spam404‎
* Anti-ThirdpartySocial
* Fanboy’s Annoyance List‎
* Fanboy’s Social Blocking List‎
* Dan Pollock’s hosts file‎
* Fanboy+Easylist-Merged Ultimate List‎
* hpHosts’ Ad and tracking servers‎
* MVPS HOSTS‎
* EasyList Germany‎

Userscripts:
* AdsBypasser
* Anti-Adblock Killer | Reek
* AntiAdware

I hope I could help now a bit more.

**Comment by maynak00** [comment]
@vinctux 
ghostery not recommended. see here: https://github.com/reek/anti-adblock-killer#help
also you're using too many filterlists.first disable ghostery.second disable all filterlists and enable 1 and test.disable and test with another. Im using Adblock Warning Removal List‎ (sometimes),Anti-Adblock Killer | Reek,EasyList,EasyPrivacy.and some manually created custom filter‎.
>Check if one of these extensions is problematic (Disable Anti-Adblock 3.1, Ghostery, Online Security Avast, Donotrackme, Privacy Badger, Disconnect, Blur, TrackerBlock, Kaspersky Anti-Banner, Freebox (Anti-pub), No Script).

**Comment by reek** [comment]
Hi,

Its ok for me.
