### ISSUE TITLE
levante-emv.com

### ISSUE THREAD

**Issue by centXcent** [reek/anti-adblock-killer#2766]
http://www.levante-emv.com/sucesos/2017/01/27/accidente-trafico-camino-moncada/1521015.html
http://imgur.com/a/TfVJj
Google Chrome
Tampermonkey
uBlock Origin
EasyList Spanish + EasyList + AakList + MVPS HOSTS

**Comment by mapx-** [comment]
add in ubo
`@@||levante-emv.com/*ads`

**Comment by centXcent** [comment]
Perfect, tested and working.
Thank you very much.

**Comment by uBlock-user** [comment]
add this in uBO - `levante-emv.com##script:inject(abort-on-property-read.js, pr_okvalida)`

**Comment by centXcent** [comment]
Ok, i've tested it and works too, is that solution more efficient?

**Comment by mapx-** [comment]
No, the first one it's simpler and easier. The injection it's useful in some complex cases not in this one.

**Comment by uBlock-user** [comment]
It's much better than blanket allowing with a key word called "ads", such enormous exception list will always be abused. Those easier solutions are the easiest solutions for abusal, remember that. Injection is useful everywhere and is a sophisticated solution rather than a lame whitelisting one which is cause of the downfall of Easylist. You already are using uBO, better use one which is precise.
