### ISSUE TITLE
www.anandabazar.com

### ISSUE THREAD

**Issue by harryqt** [reek/anti-adblock-killer#2841]
URL = http://www.anandabazar.com/national/supreme-court-likely-to-give-verdict-in-a-corruption-case-against-vk-sasikala-on-tomorrow-dgtl-1.563862

How to block it?

**Comment by uBlock-user** [comment]
cannot reproduce.

**Comment by harryqt** [comment]
@uBlock-user I did not understand what you said.

**Comment by uBlock-user** [comment]
I cannot reproduce any anti adblock intervention.

**Comment by harryqt** [comment]
@uBlock-user Oh, may I ask why? Just curios what is so unique in this case?

**Comment by uBlock-user** [comment]
Can you reproduce ? Provide some information, like a snapshot of anti adblock script in action, adblocker you use, browser version and info etc.

**Comment by harryqt** [comment]
@uBlock-user Here we go.

Snapshot = http://prntscr.com/e87ok7
Page Source Code = http://pastebin.com/DV0UHnxm
Google Chrome & Adblock Plus.

**Comment by uBlock-user** [comment]
Force update all your adblock plus filters and see if it stops.

**Comment by harryqt** [comment]
@uBlock-user Just did. Did not worked. Getting detected.

**Comment by uBlock-user** [comment]
try `@@||anandabazar.com^$generichide` and `||$third-party,script,domain=anandabazar.com`

**Comment by harryqt** [comment]
@uBlock-user Worked. 👍

**Comment by harryqt** [comment]
Just out of curiosity, how do you figure out which element to block? Just wants to know. :)

**Comment by uBlock-user** [comment]
I use uBlock Origin and I cannot reproduce, so I guess the issue only pertains to ABP and generic adblockers.

**Comment by harryqt** [comment]
Ohh. I see. Also, after adding those filters, it's blocking facebook widgets too.

**Comment by uBlock-user** [comment]
Remove the second filter and see if it still works.

**Comment by harryqt** [comment]
adding the 1st filter, does not make any difference (does not block the anti ad blocker), But adding the 2nd filter does the job but which includes other widget & 3rd party content too. (which kind of weird).

**Comment by uBlock-user** [comment]
Just remove Anti Adblocker Killer script from TamperMonkey extension and only keep the first filter and see if it works.

**Comment by harryqt** [comment]
@uBlock-user I can't remove the Anti Adblocker Killer script, I do use it a lot.

**Comment by uBlock-user** [comment]
It's outdated and no longer updated. Reek went MIA and is no longer active and all anti adblock scripts can be patched via filters, you don't need it.

**Comment by harryqt** [comment]
Removed Anti Adblocker Killer script, only kept 1st filter. Did not worked. ad blocker detected. :(

**Comment by uBlock-user** [comment]
Well then add the second filter back again. If you want facebook widgets and buttons, you will have create those exception filters separately.

**Comment by jspenguin2017** [comment]
Looks like they are expecting `canRunAds` to be false (or undefined), but it is set to `true` by AAK Script.

**Comment by harryqt** [comment]
@X01X012013 So... Fix?

**Comment by jspenguin2017** [comment]
@Dibbyo456 
Use my script instead? https://x01x012013.github.io/AdBlockProtector/

**Comment by harryqt** [comment]
@X01X012013 Did not worked.

**Comment by jspenguin2017** [comment]
@Dibbyo456 What's your setup? It works fine on my machine.

**Comment by uBlock-user** [comment]
They're setting `canRunAds` true inline and then setting false in this script http://www.anandabazar.com/js/anandabazar-bootstrap/gads.js as false which is also loaded inline, doesn't make sense. 

Also ABP cannot block inline-scripts, so it will always be loaded.

**Comment by jspenguin2017** [comment]
@uBlock-user Inline-script blocking only work on FireFox.

**Comment by jspenguin2017** [comment]
OK, I'll lock the variable to false.

**Comment by uBlock-user** [comment]
@X01X012013 works in Chromium with uBO. not just Firefox.

**Comment by jspenguin2017** [comment]
@uBlock-user 
https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering
That's not what uBlock Origin's docs says.

**Comment by uBlock-user** [comment]
@X01X012013 You misunderstand. That's different.

What is meant is I can do this - `||example.com^$inline-script` and it will work on uBO only. ABP can't use that filter as they don't support inline-script blocking. 

Now, coming to Inline-script Tag Filtering which is a whole another thing where I can block an individual inline-script. It would have worked in Chromium if the devs would not have removed. FYI - https://github.com/whatwg/html/issues/943

**Comment by jspenguin2017** [comment]
@uBlock-user That blocks all inline scripts, I wouldn't call that "working". Don't get me wrong, I use uBlock Origin too, it is better than ABP. And I hope Chromium people will eventually add `onbeforescriptexecute` event so we don't need to use hacky ways to patch inline scripts. 
@Dibbyo456 Can you try version 5.35 of my script? it should<sup>tm</sup> work now.

**Comment by uBlock-user** [comment]
@X01X012013 Yes, an unfortunate consequence, that's why I only use it if I'm out of options and as a last resort fix, it does stop anti adblock scripts in most cases and sometimes it breaks other things too like login and register systems, comment systems, depending on the website. To me, it's an alternate fix, and I can live with that. So it works for me. Chromium devs are never going to add them, Google has already decided, not to give users such power to disable specific inline-scripts. 

Infact Firefox may remove it soon - https://bugzilla.mozilla.org/show_bug.cgi?id=1286822

**Comment by jspenguin2017** [comment]
@uBlock-user Have a look at `patchHTML()` and `crashScript()` of the core library of my script, it's kind of hacky but it works. 
`crashScript()` takes in a sample of the the script and crash it by syntax error, it only affect the specific inline script block (can only crash one block for now). 
`patchHTML()` is more complicate and may require regular expression (supports more complex patching).

**Comment by uBlock-user** [comment]
@X01X012013 I'm no JS expert, but I believe you. The real reason I started using AAK because uBO wasn't able to patch every anti adblock script back in 2015, as it brand new and had been released only few months before I started using it, so options were limited and I was a complete newbie and had no clue how to check what was happening and how can I patch the scripts, so to avoid any hassle I installed AAK and things got better as it the job for me. 

Time passed by and gorhill kept adding new features and I learnt new ways of patching scripts and how to check the honeytrap they lay around catching users off-guard and I found that I could live without AAK, but I still kept in hopes that I will remove one day but not at that time when I won't need it.

By the time July 2016 came back I was thinking about discarding TM and AAK altogether as I dislike having multiple extensions for a single cause and that very time, Reek left, so I finally decided to delete and I did that day itself. After I removed it, I found that the websites I visted which had AA were already patched by filters, so I really don't need AAK after all and those which were patched, I tried and patched them myself or report to uAssets in the hopes that gorhill and contributors would help me patch it.
