### ISSUE TITLE
Faz.de

### ISSUE THREAD

**Issue by lul14789635** [reek/anti-adblock-killer#3684]
Hey. I'd like to report an anti adblock on this news site for every article:
Just click an article to see

http://www.faz.net/aktuell/

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by jspenguin2017** [comment]
I don't see anything wrong neither.

**Comment by TheRealSourceSeeker** [comment]
@lul14789635 
Have the same problem, but found a solution!
faz.net complains about AdBlock Plus, so, the moment I found this issue thread, i just tried uBlock Origin because of the name of @uBlock-user .
Well, with "uBlock Origin" faz.net works, while with "AdBlock Plus" it doesn't!
Try it! Hope this helps! In my case it did :-)

**Comment by FlavourDave92** [comment]
have the same problem with Adblock.
