### ISSUE TITLE
cryptospot.me

### ISSUE THREAD

**Issue by krunox123** [reek/anti-adblock-killer#493]
https://cryptospot.me/
http://imgur.com/RW0JzPz
Google Chrome & UC Browser
Tampermonkey
uBlock Origin
EasyList + Anti-Adblock Kiler

**Comment by maynak00** [comment]
are you using another filters? because ads blocked and no adblocker detected message for me.
Chromium x64
Tampermonkey BETA+ https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/
uBlock Origin
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎

**Comment by krunox123** [comment]
Only EasyList and Anti-AdBlock Killer ads filter is enabled in my list...

Oh, yeah... EasyPrivacy too.
Sorry, I missed that one.
