### ISSUE TITLE
Anti-adblock killer filter list (one rule) interfares with Firefox 40's Get Add-ons display

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#540]
Just "updated" (?) to FF40 and noticed that its Addon manger "Get Add-ons" no longer works (no content shown).  I tracked it down to the AskList's rule "/anti-adblock$~stylesheet".  If I disable that one rule the Get Addons display shows.

FF40 On Mac OSX 10.6.7.

Update:
I just tested this on FF39.0.3 and the problem is there too.  So I don't know how long this problem has been around since I rarely visit the "Get Add-ons" tab in the Add-ons manager.  I only noticed it this time because I saw FF40 screwed around with the Add-ons manager a little bit and was looking to see if there were any other changes in it.

Note, since the Get Addons page is really not that important (at least to me, which is why I only just noticed it), and if it is deemed that the "/anti-adblock$~stylesheet" rule is critical then that's OK. Leave it alone.  But I thought I would mention this effect anyway.

**Comment by Watilin** [comment]
I'm on FF40.0.2/Win7 and was able to reproduce the bug as well.

When you access the “Get Add-ons” tab, FF makes a request to https://services.addons.mozilla.org/fr/firefox/discovery/pane/40.0.2/WINNT/normal (actually, the `extensions.webservice.discoverURL` entry in *about:config*) with an URL-encoded version of a JSON object containing info about all installed add-ons and userscripts.

Here's an example:
```javascript
{
  '{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}': {
    'name': 'Adblock Plus',
    'version': '2.6.10',
    'type': 'extension',
    'userDisabled': false,
    'isCompatible': true,
    'isBlocklisted': false
  },
  '{e4a8a97b-f2ed-450b-b12d-ee082ba24781}': {
    'name': 'Greasemonkey',
    'version': '3.3',
    'type': 'extension',
    'userDisabled': false,
    'isCompatible': true,
    'isBlocklisted': false
  },
  '{972ce4c6-7e08-4474-a285-3208198ce6fd}': {
    'name': 'Default',
    'version': '40.0.2',
    'type': 'theme',
    'userDisabled': true,
    'isCompatible': true,
    'isBlocklisted': false
  },
  'recommended-3@personas.mozilla.org': {
    'name': 'Douce lumière',
    'version': '1.0',
    'type': 'theme',
    'userDisabled': false,
    'isCompatible': true,
    'isBlocklisted': false
  },
  'gmp-gmpopenh264': {
    'name': 'Codec vidéo OpenH264 fourni par Cisco Systems, Inc.',
    'version': '1.4',
    'type': 'plugin',
    'userDisabled': true,
    'isCompatible': true,
    'isBlocklisted': false
  },
  '{12b61fb1-c5d3-1ec9-b89c-692a67f2a6bc}': {
    'name': 'Shockwave Flash',
    'version': '18.0.0.232',
    'type': 'plugin',
    'userDisabled': 'askToActivate',
    'isCompatible': true,
    'isBlocklisted': false
  },
  '{5e3aa2b9-3b9d-fbbe-e217-a608e47bfdfe}': {
    'name': 'Unity Player',
    'version': '4.6.1.51269',
    'type': 'plugin',
    'userDisabled': 'askToActivate',
    'isCompatible': true,
    'isBlocklisted': false
  },
  'https://userscripts.org/scripts/show/155840/Anti-Adblock Killer | Reek@greasespot.net': {
    'name': 'Anti-Adblock Killer | Reek',
    'version': '8.3',
    'type': 'greasemonkey-user-script',
    'userDisabled': true,
    'isCompatible': true,
    'isBlocklisted': false
  }
}
```
It's easy to find out that the substring `https://userscripts.org/scripts/show/155840/Anti-Adblock Killer` matches the `/anti-adblock$~stylesheet` filter. This is an annoying bug as it is caused by a sort of self reference and might occur in other parts of the browser/other browsers as well.

 I can't find a good reason why FF is phoning home all this data— especially when I have the “data collecting” option turned off. This is kind of deceptive and I'm more used to see such a behavior with Google Chrome. In my opinion this is a regression with Firefox, not with Aak, but I guess we're the ones who'll have to fix things :|

I think simply adding `,~domain=mozilla.org` to the filter will do it.

**Comment by reek** [comment]
Thanks again Watilin :+1:

**Comment by reek** [comment]
Fixed, update AakList
