### ISSUE TITLE
ctenetwork.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#713]
Hi, 

![ctenetwork.com](https://cloud.githubusercontent.com/assets/1873139/10867313/373e05cc-805b-11e5-953d-1744d463b515.png)

on : 
```
http://www.arcadeupload.com/
http://www.gamersgallery.com/
http://gamesforwork.com/
```
filter:
`||all.ctenetwork.com^`

Thanks!

**Comment by SMed79** [comment]
`||ctenetwork.com^$third-party`
https://hg.adblockplus.org/easylist/rev/a7f66bd0792e#l1.12

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by sbtHUB** [comment]
I am confused.  Why is a request for donation classified as Anti-Adblock?  You all know that Internet servers and the hosting of sites take resources and some are expensive to support, so what is wrong with a request for a donation when ads are blocked?

**Comment by SMed79** [comment]
@sbtHUB https://easylist.adblockplus.org/blog/2013/05/10/anti-adblock-guide-for-site-admins

**Comment by alexander255** [comment]
Thank you @SMed79 !
I was just about to write up something similar and wasn't aware of the document you have provided. 

@reek
Do you agree with the rules outlined in https://easylist.adblockplus.org/blog/2013/05/10/anti-adblock-guide-for-site-admins ?
If so: Would you consider adding a link to these rules to the [Reporting Guide](https://github.com/reek/anti-adblock-killer/wiki/Report-Guide), so that it's clear to users which content will and will not be blocked/fixed by AAK?
