### ISSUE TITLE
Midori suppport

### ISSUE THREAD

**Issue by smilzoboboz** [reek/anti-adblock-killer#810]
It would be great to have midori support. If it doesn't require a lot of work I think it would be worth a try.

**Comment by reek** [comment]
Hi,

What adblocker and scriptManger use with Midori ?

**Comment by SMed79** [comment]
* The AdBlock extension from Midori uses the same [subscriptions lists](http://adblockplus.org/subscriptions) as the AdBlock Plus.
* Midori User scripts and styles http://midori-browser.org/faqs/#user_scripts_and_styles.

**Comment by reek** [comment]
@SMed79 
Thanks for documentation.

@smilzoboboz 
From what I read, If Midori does not work or it works in limited way with AakScript.

It's because, Midori doesn't support advanced metadata and does not support Greasemonkey API
or AakScript need this feature to work well.

It's to developers Midori improve support for userscripts.

**Comment by SMed79** [comment]
demo: 

![demo midori](https://cloud.githubusercontent.com/assets/1873139/11605176/ec36c772-9af8-11e5-931f-4642428bdc0f.png)

**Comment by smilzoboboz** [comment]
Understood, Midori supports Greasemonkey API but it's possible that it has no full coverage of the whole API.
I just asked because it's the only full-gtk3-based browser with adblock+scripting functionality (among others) I know of.

Thank you anyway.

**Comment by reek** [comment]
@smilzoboboz 
I made some changes in house, just to make it work so limited (due to the limitation of Midori), so some anti-adblock will not be neutralized

**Comment by smilzoboboz** [comment]
It works! Thank you so much for the update.
