### ISSUE TITLE
[NEWS] ASUS' mobile devices will ship with built-in ad blocking

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#885]
http://www.engadget.com/2015/12/23/asus-devices-ship-with-ad-blocking/

**Comment by RoxKilly** [comment]
Don't think this is a smart move by ASUS; I'm specifically talking about turning ad-blocking ON by default. When a user goes to a site, it's the browser's job to execute the user's command to load all the resources linked to that site unless the user has expressed a different choice.

I think a better execution would be to ask the user the first time the browser loads whether she wants to turn on Do-Not-Track and whether she wants to turn on Ad-blocking. It should be user-choice.

I also question the selection of Adblock Plus when there are several [good alternatives](https://www.raymond.cc/blog/10-ad-blocking-extensions-tested-for-best-performance/view-all/).  Some clarity into how this choice was made would be welcome.  Specifically, I think this development will make the company behind Adblock Plus more powerful by giving advertisers yet another incentive to pay so that their ads will be included in Adblock Plus "Acceptable Ads".

**Comment by xxcriticxx** [comment]
maybe asus paid $$$
